# -*- coding: utf-8 -*-
"""natural_language_processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16eTeuIfCCa4_DTayhvMIBlpcefbUdG6C

# Natural Language Processing

## Importing the libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""## Importing the dataset"""

dataset = pd.read_csv('Restaurant_Reviews.tsv', delimiter = '\t', quoting = 3)

"""## Cleaning the texts"""

import re
import nltk
nltk.download('stopwords')#if an any type of words
from nltk.corpus import stopwords#importing in our model
from nltk.stem.porter import PorterStemmer#stemming means ki loved ko love ,increasing ko increase,keeping only stem words
corpus = []
for i in range(0, 1000):#1000 rows hai
  review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i])# anything apart the alphabets substitute it with space
  review = review.lower()#convert all to lower case
  review = review.split()#split the sentence into words
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')#dont include not
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]#stemming all word if not in stopwords
  review = ' '.join(review)#joining them with space in between
  corpus.append(review)#appending them in the list formed

print(corpus)

"""## Creating the Bag of Words model"""

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, -1].values

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

"""## Training the Naive Bayes model on the Training set"""

from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

"""## Predicting the Test set results"""

y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

"""## Making the Confusion Matrix"""

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

